show_downloads: true

# Site title
title: My GitHub Page

# Site description
description: A blog hosted on GitHub Pages using Jekyll

# Base URL of your site
baseurl: "/my-blog" # For a personal or organization site, leave this blank. For a project site, set this to "/<repository-name>"

# URL of your site
url: "https://<username>.github.io" # Replace <username> with your GitHub username

# Theme to use (this uses the default Jekyll theme)
theme: minima

# Permalink settings for blog posts
permalink: /:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - README.md

# Markdown processor
markdown: kramdown

# Include the following files in the build
include:
  - _posts
  - _pages

# Set your timezone
timezone: "UTC"

